// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $gallery_index from "./routes/gallery/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $studio_index from "./routes/studio/index.tsx";
import * as $api_artists from "./routes/api/artists.ts";
import * as $api_products from "./routes/api/products.ts";
import * as $StudioCanvas from "./islands/StudioCanvas.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/gallery/index.tsx": $gallery_index,
    "./routes/index.tsx": $index,
    "./routes/studio/index.tsx": $studio_index,
    "./routes/api/artists.ts": $api_artists,
    "./routes/api/products.ts": $api_products,
  },
  islands: {
    "./islands/StudioCanvas.tsx": $StudioCanvas,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
