-- =============================================================================
-- fineprint.hu — Supabase Database Schema
-- PostgreSQL / Supabase SQL (run in Supabase SQL Editor)
-- =============================================================================

-- Enable UUID extension
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- ARTISTS
-- ---------------------------------------------------------------------------
create table if not exists artists (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  bio           text not null default '',
  avatar_url    text not null default '',
  portfolio_url text not null default '',
  created_at    timestamptz not null default now()
);

comment on table artists is 'Independent artists who list work on fineprint.hu';

-- ---------------------------------------------------------------------------
-- PRODUCTS
-- Type discriminator: "physical" | "algorithm_preset"
-- ---------------------------------------------------------------------------
create table if not exists products (
  id          uuid primary key default gen_random_uuid(),
  artist_id   uuid not null references artists(id) on delete cascade,
  title       text not null,
  description text not null default '',
  type        text not null check (type in ('physical', 'algorithm_preset')),
  price_cents integer not null check (price_cents >= 0),
  currency    text not null default 'HUF' check (currency in ('HUF', 'EUR', 'USD')),
  image_url   text not null default '',
  in_stock    boolean not null default true,
  -- Physical print metadata (null for algorithm_preset)
  dimensions_mm   jsonb,     -- { "width": 400, "height": 500 }
  paper_gsm       integer,
  paper_type      text,
  edition_size    integer,
  edition_number  integer,
  is_signed       boolean not null default false,
  -- Algorithm preset metadata (null for physical)
  algorithm_id    text,      -- matches key in ALGORITHMS registry
  preset_params   jsonb,     -- parameter overrides as JSON
  preview_url     text,
  created_at  timestamptz not null default now()
);

comment on table products is 'Physical fine art prints and algorithm presets for sale';
comment on column products.type is '"physical" = fine art print; "algorithm_preset" = generative algorithm seed';

create index idx_products_type      on products(type);
create index idx_products_artist_id on products(artist_id);
create index idx_products_in_stock  on products(in_stock);

-- ---------------------------------------------------------------------------
-- USER PROFILES (extends Supabase auth.users)
-- ---------------------------------------------------------------------------
create table if not exists profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url   text not null default '',
  created_at   timestamptz not null default now()
);

comment on table profiles is 'Public user profile data, linked to Supabase auth.users';

-- Automatically create a profile row when a new user signs up
create or replace function handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles(id)
  values (new.id);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- ---------------------------------------------------------------------------
-- USER CREATIONS
-- Art generated by users in the Generative Studio
-- ---------------------------------------------------------------------------
create table if not exists user_creations (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references profiles(id) on delete cascade,
  algorithm_id  text not null,
  params        jsonb not null default '{}',
  render_url    text,
  ordered_print boolean not null default false,
  created_at    timestamptz not null default now()
);

comment on table user_creations is 'Art pieces generated by users in the Generative Studio';

create index idx_user_creations_user_id on user_creations(user_id);

-- ---------------------------------------------------------------------------
-- ORDERS
-- ---------------------------------------------------------------------------
create table if not exists orders (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references profiles(id) on delete restrict,
  status                   text not null default 'pending'
                             check (status in ('pending', 'paid', 'fulfilled', 'shipped', 'cancelled')),
  total_cents              integer not null check (total_cents >= 0),
  currency                 text not null default 'HUF',
  stripe_payment_intent_id text unique,
  shipping_address         jsonb,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

comment on table orders is 'Customer orders for physical prints and algorithm presets';

create index idx_orders_user_id on orders(user_id);
create index idx_orders_status  on orders(status);

-- ---------------------------------------------------------------------------
-- ORDER ITEMS
-- ---------------------------------------------------------------------------
create table if not exists order_items (
  id         uuid primary key default gen_random_uuid(),
  order_id   uuid not null references orders(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  quantity   integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  variant    text,
  -- For studio prints: link to the user creation
  user_creation_id uuid references user_creations(id) on delete set null
);

comment on table order_items is 'Line items within an order';

create index idx_order_items_order_id on order_items(order_id);

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------

alter table artists       enable row level security;
alter table products      enable row level security;
alter table profiles      enable row level security;
alter table user_creations enable row level security;
alter table orders        enable row level security;
alter table order_items   enable row level security;

-- Artists and products are publicly readable
create policy "Public read artists"  on artists  for select using (true);
create policy "Public read products" on products for select using (true);

-- Profiles: users can read any profile, but only update their own
create policy "Public read profiles"  on profiles for select using (true);
create policy "Own profile update"    on profiles for update using (auth.uid() = id);

-- User creations: owner only
create policy "Own creations read"   on user_creations for select using (auth.uid() = user_id);
create policy "Own creations insert" on user_creations for insert with check (auth.uid() = user_id);
create policy "Own creations update" on user_creations for update using (auth.uid() = user_id);

-- Orders: owner only
create policy "Own orders read"   on orders for select using (auth.uid() = user_id);
create policy "Own orders insert" on orders for insert with check (auth.uid() = user_id);
create policy "Own order items read" on order_items for select
  using (exists (select 1 from orders o where o.id = order_id and o.user_id = auth.uid()));
