// =============================================================================
// Shared TypeScript types for fineprint.hu
// =============================================================================

/** Product type discriminator */
export type ProductType = "physical" | "algorithm_preset";

/** Supported currencies */
export type Currency = "HUF" | "EUR" | "USD";

/** Order status */
export type OrderStatus = "pending" | "paid" | "fulfilled" | "shipped" | "cancelled";

// ---------------------------------------------------------------------------
// Artist
// ---------------------------------------------------------------------------

export interface Artist {
  /** UUID */
  id: string;
  name: string;
  bio: string;
  avatarUrl: string;
  portfolioUrl: string;
  /** ISO-8601 */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Product
// ---------------------------------------------------------------------------

export interface Product {
  /** UUID */
  id: string;
  artistId: string;
  title: string;
  description: string;
  /** Discriminates physical prints vs algorithm presets */
  type: ProductType;
  /** Price in smallest currency unit (e.g. fillér for HUF) */
  priceCents: number;
  currency: Currency;
  imageUrl: string;
  inStock: boolean;
  /** Additional metadata specific to physical prints */
  printDetails?: PrintDetails;
  /** Additional metadata specific to algorithm presets */
  presetDetails?: PresetDetails;
  /** ISO-8601 */
  createdAt: string;
}

export interface PrintDetails {
  /** Width × Height in mm */
  dimensionsMm: { width: number; height: number };
  paperGsm: number;
  paperType: string;
  editionSize?: number;
  editionNumber?: number;
  isSigned: boolean;
}

export interface PresetDetails {
  /** Identifier of the generative algorithm this preset applies to */
  algorithmId: string;
  /** Serialised parameter overrides as JSON */
  params: Record<string, unknown>;
  /** Low-res preview image of the generated output */
  previewUrl: string;
}

// ---------------------------------------------------------------------------
// UserCreation
// ---------------------------------------------------------------------------

/** A piece of art generated by a user in the Generative Studio */
export interface UserCreation {
  /** UUID */
  id: string;
  userId: string;
  algorithmId: string;
  /** Serialised parameters used to produce this creation */
  params: Record<string, unknown>;
  /** High-res render URL (cloud storage) */
  renderUrl?: string;
  /** Whether the user has ordered a physical print of this creation */
  orderedPrint: boolean;
  /** ISO-8601 */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Cart
// ---------------------------------------------------------------------------

export interface CartItem {
  product: Product;
  quantity: number;
  /** For physical prints: requested size/paper variant */
  variant?: string;
}

export interface Cart {
  items: CartItem[];
  totalCents: number;
  currency: Currency;
}

// ---------------------------------------------------------------------------
// Order
// ---------------------------------------------------------------------------

export interface Order {
  /** UUID */
  id: string;
  userId: string;
  items: CartItem[];
  status: OrderStatus;
  totalCents: number;
  currency: Currency;
  /** Stripe PaymentIntent ID */
  stripePaymentIntentId?: string;
  shippingAddress?: ShippingAddress;
  /** ISO-8601 */
  createdAt: string;
  updatedAt: string;
}

export interface ShippingAddress {
  recipientName: string;
  line1: string;
  line2?: string;
  city: string;
  postalCode: string;
  country: string;
}
